// Generated by gencpp from file dy_avoidobs/localtraj.msg
// DO NOT EDIT!


#ifndef DY_AVOIDOBS_MESSAGE_LOCALTRAJ_H
#define DY_AVOIDOBS_MESSAGE_LOCALTRAJ_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Point.h>

namespace dy_avoidobs
{
template <class ContainerAllocator>
struct localtraj_
{
  typedef localtraj_<ContainerAllocator> Type;

  localtraj_()
    : car_id(0)
    , traj_id(0)
    , start_time()
    , pos_pts()  {
    }
  localtraj_(const ContainerAllocator& _alloc)
    : car_id(0)
    , traj_id(0)
    , start_time()
    , pos_pts(_alloc)  {
  (void)_alloc;
    }



   typedef int32_t _car_id_type;
  _car_id_type car_id;

   typedef int64_t _traj_id_type;
  _traj_id_type traj_id;

   typedef ros::Time _start_time_type;
  _start_time_type start_time;

   typedef std::vector< ::geometry_msgs::Point_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::geometry_msgs::Point_<ContainerAllocator> >> _pos_pts_type;
  _pos_pts_type pos_pts;





  typedef boost::shared_ptr< ::dy_avoidobs::localtraj_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::dy_avoidobs::localtraj_<ContainerAllocator> const> ConstPtr;

}; // struct localtraj_

typedef ::dy_avoidobs::localtraj_<std::allocator<void> > localtraj;

typedef boost::shared_ptr< ::dy_avoidobs::localtraj > localtrajPtr;
typedef boost::shared_ptr< ::dy_avoidobs::localtraj const> localtrajConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::dy_avoidobs::localtraj_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::dy_avoidobs::localtraj_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::dy_avoidobs::localtraj_<ContainerAllocator1> & lhs, const ::dy_avoidobs::localtraj_<ContainerAllocator2> & rhs)
{
  return lhs.car_id == rhs.car_id &&
    lhs.traj_id == rhs.traj_id &&
    lhs.start_time == rhs.start_time &&
    lhs.pos_pts == rhs.pos_pts;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::dy_avoidobs::localtraj_<ContainerAllocator1> & lhs, const ::dy_avoidobs::localtraj_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace dy_avoidobs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::dy_avoidobs::localtraj_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::dy_avoidobs::localtraj_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::dy_avoidobs::localtraj_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::dy_avoidobs::localtraj_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::dy_avoidobs::localtraj_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::dy_avoidobs::localtraj_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::dy_avoidobs::localtraj_<ContainerAllocator> >
{
  static const char* value()
  {
    return "3dc77ae9fb11c09e1886c8d863ff6e72";
  }

  static const char* value(const ::dy_avoidobs::localtraj_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x3dc77ae9fb11c09eULL;
  static const uint64_t static_value2 = 0x1886c8d863ff6e72ULL;
};

template<class ContainerAllocator>
struct DataType< ::dy_avoidobs::localtraj_<ContainerAllocator> >
{
  static const char* value()
  {
    return "dy_avoidobs/localtraj";
  }

  static const char* value(const ::dy_avoidobs::localtraj_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::dy_avoidobs::localtraj_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 car_id\n"
"\n"
"int64 traj_id\n"
"time start_time\n"
"\n"
"\n"
"geometry_msgs/Point[] pos_pts\n"
"\n"
"\n"
"\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
;
  }

  static const char* value(const ::dy_avoidobs::localtraj_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::dy_avoidobs::localtraj_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.car_id);
      stream.next(m.traj_id);
      stream.next(m.start_time);
      stream.next(m.pos_pts);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct localtraj_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::dy_avoidobs::localtraj_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::dy_avoidobs::localtraj_<ContainerAllocator>& v)
  {
    s << indent << "car_id: ";
    Printer<int32_t>::stream(s, indent + "  ", v.car_id);
    s << indent << "traj_id: ";
    Printer<int64_t>::stream(s, indent + "  ", v.traj_id);
    s << indent << "start_time: ";
    Printer<ros::Time>::stream(s, indent + "  ", v.start_time);
    s << indent << "pos_pts[]" << std::endl;
    for (size_t i = 0; i < v.pos_pts.size(); ++i)
    {
      s << indent << "  pos_pts[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::geometry_msgs::Point_<ContainerAllocator> >::stream(s, indent + "    ", v.pos_pts[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // DY_AVOIDOBS_MESSAGE_LOCALTRAJ_H
